apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: 
    port: 80
    #NodePort: 30090
  selector:
    service: {{ .Values.service.name }}
  type: {{ .Values.service.type }}
