apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.nginxpv.pvname }}
    namespace: {{ .Values.namespace }}
spec:
    capacity:
        storage: 2Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: {{ .Values.nginxpv.classname }}
    mountOptions:
        - hard
    nfs:
        path: {{ .Values.nginxpv.nfspath }}
        server: {{.Values.nginxpv.nfsserver }}
    