apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: {{ .Values.servicename }}
  name: {{ .Values.servicename }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Values.servicename }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: {{ .Values.servicename }}
    spec:
      containers:
      - image: {{ .Values.deployment.image }}:{{ .Values.deployment.version }}
        imagePullPolicy: ""
        name: {{ .Values.servicename }}
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-nfs
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nginx-nfs
        persistentVolumeClaim:
          claimName: nginx-pvc
status: {}  