namespace: myproject2

deployment:
  replicas: 2
  image: 192.168.56.250:8082/repository/myproject2
  tag: s0.0.1-24
  app_name: myproject2
  imagePullPolicy: Always
  containerPort: 8080
  protocol: TCP

service:
  name: service-mp2-dev
  port: 8080
  nodePort: 30002
  selector_app: automation
  service_type: NodePort
  protocol: TCP
  
secret:
  name: duclo-repo

canaryService:
  name: canary-myproject2
  port: 8080
  nodePort: 30012
  selector_app: canary-myproject2
  service_type: NodePort
  protocol: TCP

canaryDeploy:
  replicas: 0
  image: 192.168.56.250:8082/repository/myproject2
  tag: s0.0.1-24
  app_name: canary-myproject2
  imagePullPolicy: Always
  containerPort: 8080
  protocol: TCP

serAccount:
  name: myproject2-sa
