apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.databasepv.pvname }}
    namespace: {{ .Values.namespace }}
spec:
    capacity:
        storage: 2Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: {{ .Values.databasepv.classname }}
    mountOptions:
        - hard
    nfs:
        path: {{ .Values.databasepv.nfspath }}
        server: {{ .Values.databasepv.nfsserver }}
       
