apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Values.service.selector_app }}
  type: {{ .Values.service.service_type }}

