apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mydemo
spec:
  selector:
    matchLabels:
      app:  mydemo
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: mydemo
    spec:
      containers:
      - name: devops-demo
        image: mistryparas/devops-demo:v4.12
        ports:
        - containerPort: 8080
          protocol: TCP
