namespace: myproject1

deployment:
  replicas: 4
  image: 192.168.56.250:8082/repository/myproject1
  tag: s0.0.1-5
  app_name: myproject1
  imagePullPolicy: Always
  containerPort: 8080
  protocol: TCP

service:
  name: service-myproject-dev
  port: 8080
  nodePort: 30001
  selector_app: myprojec1
  service_type: NodePort
  protocol: TCP
  
secret:
  name: myproject1-repo

canaryService:
  name: canary-myproject1
  port: 8080
  nodePort: 30011
  selector_app: canary-myproject1
  service_type: NodePort
  protocol: TCP

canaryDeploy:
  replicas: 0
  image: 192.168.56.250:8082/repository/myproject1
  tag: s0.0.1-5
  app_name: canary-myproject1
  imagePullPolicy: Always
  containerPort: 8080
  protocol: TCP

serAccount:
  name: myproject1-sa
