apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: 
    port: 80
  selector:
    service: {{ .Values.servicename }}
  type: {{ .Values.service.type }}
  